### ISSUE TITLE
テクスチャがおかしい

### ISSUE THREAD

**Issue by kawaemon** [ReiRokusanami0010/TinkersGunsConstruction#6]
パーツのテクスチャがステンシルテーブルのテクスチャと一緒になってる？

<img width="167" alt="Screen Shot 2019-06-08 at 19 55 09" src="https://user-images.githubusercontent.com/34652535/59146271-933b3780-8a27-11e9-89d6-3b799eb72fa3.png">

<img width="1680" alt="Screen Shot 2019-06-08 at 19 54 38" src="https://user-images.githubusercontent.com/34652535/59146216-86b6df00-8a27-11e9-8022-c6290555b8f9.png">

**Comment by HostaPlantain** [comment]
マテリアルが適応されてないパーツはそんな感じの見た目になるから、そのパーツを使ったツールを作った後に確認してみて。
